/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ClienteTCP;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import org.json.JSONObject;

/**
 *
 * @author Carlos
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelConfiguração = new javax.swing.JPanel();
        jButtonConectarRFID = new javax.swing.JButton();
        jButtonCadastrarCarros = new javax.swing.JButton();
        jButtonCadastrarEquipes = new javax.swing.JButton();
        jButtonCadastrarPilotos = new javax.swing.JButton();
        jButtonCadastrarPistas = new javax.swing.JButton();
        jButtonConfigurarPartida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanelCadastroCarros = new javax.swing.JPanel();
        jButtonVoltarConfiguracaoCadastroCarros = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCorDoCarro = new javax.swing.JTextField();
        jTextFieldModeloDoCarro = new javax.swing.JTextField();
        jTextFieldMarcaDoCarro = new javax.swing.JTextField();
        jTextFieldNumeroDoCarro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jPanelCadastroEquipe = new javax.swing.JPanel();
        jButtonVoltarConfiguracaoCadastroEquipe = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldIDdaEquipe = new javax.swing.JTextField();
        jTextFieldNacionalidade = new javax.swing.JTextField();
        jTextFieldAno = new javax.swing.JTextField();
        jTextFieldNomeDaEquipe = new javax.swing.JTextField();
        jTextFieldApelido = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jPanelConfigurarPartida = new javax.swing.JPanel();
        jButtonVoltarConfiguracaoConfigurarPartida = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldNumeroDeVoltas = new javax.swing.JTextField();
        jTextFieldPista = new javax.swing.JTextField();
        jTextFieldHoras = new javax.swing.JTextField();
        jTextFieldMinutos = new javax.swing.JTextField();
        jTextFieldSegundos = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jPanelCadastroPiloto = new javax.swing.JPanel();
        jButtonVoltarConfiguracaoCadastroPiloto = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldNomeDoPiloto = new javax.swing.JTextField();
        jTextFieldEquipeDoPiloto = new javax.swing.JTextField();
        jTextFieldIDDoPiloto = new javax.swing.JTextField();
        jTextFieldNacionalidadeDoPiloto = new javax.swing.JTextField();
        jTextFieldApelidoDoPiloto = new javax.swing.JTextField();
        jTextFieldDataDeNascimento = new javax.swing.JTextField();
        jTextFieldCarro = new javax.swing.JTextField();
        jTextFieldEquipe = new javax.swing.JTextField();
        jComboBoxStatusPiloto = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jPanelCadastroPista = new javax.swing.JPanel();
        jButtonVoltarConfiguracaoCadastroPista = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextFieldIDPista = new javax.swing.JTextField();
        jTextFieldPaisDaPista = new javax.swing.JTextField();
        jTextFieldNomeDaPista = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanelConectarRFID = new javax.swing.JPanel();
        jButtonVoltarConfiguracaoRFID = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jTextFieldAntena = new javax.swing.JTextField();
        jTextFieldIP = new javax.swing.JTextField();
        jTextFieldPortaDeRede = new javax.swing.JTextField();
        jTextFieldTaxaEmBaud = new javax.swing.JTextField();
        jTextFieldPotenciaDoSinal = new javax.swing.JTextField();
        jTextFieldProtocolo = new javax.swing.JTextField();
        jTextFieldPortaSerial = new javax.swing.JTextField();
        jTextFieldRegiao = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanelPrincipal.setRequestFocusEnabled(false);
        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jPanelConfiguração.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanelConfiguração.setLayout(null);

        jButtonConectarRFID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConectarRFID.setForeground(new java.awt.Color(0, 0, 204));
        jButtonConectarRFID.setText("Conectar RFID");
        jButtonConectarRFID.setMaximumSize(new java.awt.Dimension(134, 23));
        jButtonConectarRFID.setMinimumSize(new java.awt.Dimension(134, 23));
        jButtonConectarRFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarRFIDActionPerformed(evt);
            }
        });
        jPanelConfiguração.add(jButtonConectarRFID);
        jButtonConectarRFID.setBounds(558, 58, 160, 30);

        jButtonCadastrarCarros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadastrarCarros.setForeground(new java.awt.Color(0, 0, 204));
        jButtonCadastrarCarros.setText("Cadastrar Carro");
        jButtonCadastrarCarros.setMaximumSize(new java.awt.Dimension(134, 23));
        jButtonCadastrarCarros.setMinimumSize(new java.awt.Dimension(134, 23));
        jButtonCadastrarCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarCarrosActionPerformed(evt);
            }
        });
        jPanelConfiguração.add(jButtonCadastrarCarros);
        jButtonCadastrarCarros.setBounds(559, 102, 160, 30);

        jButtonCadastrarEquipes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadastrarEquipes.setForeground(new java.awt.Color(0, 0, 204));
        jButtonCadastrarEquipes.setText("Cadastrar Equipe");
        jButtonCadastrarEquipes.setMaximumSize(new java.awt.Dimension(134, 23));
        jButtonCadastrarEquipes.setMinimumSize(new java.awt.Dimension(134, 23));
        jButtonCadastrarEquipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarEquipesActionPerformed(evt);
            }
        });
        jPanelConfiguração.add(jButtonCadastrarEquipes);
        jButtonCadastrarEquipes.setBounds(558, 225, 160, 30);

        jButtonCadastrarPilotos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadastrarPilotos.setForeground(new java.awt.Color(0, 0, 204));
        jButtonCadastrarPilotos.setText("Cadastrar Piloto");
        jButtonCadastrarPilotos.setMaximumSize(new java.awt.Dimension(134, 23));
        jButtonCadastrarPilotos.setMinimumSize(new java.awt.Dimension(134, 23));
        jButtonCadastrarPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarPilotosActionPerformed(evt);
            }
        });
        jPanelConfiguração.add(jButtonCadastrarPilotos);
        jButtonCadastrarPilotos.setBounds(559, 143, 160, 30);

        jButtonCadastrarPistas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCadastrarPistas.setForeground(new java.awt.Color(0, 0, 204));
        jButtonCadastrarPistas.setText("Cadastrar Pista");
        jButtonCadastrarPistas.setMaximumSize(new java.awt.Dimension(134, 23));
        jButtonCadastrarPistas.setMinimumSize(new java.awt.Dimension(134, 23));
        jButtonCadastrarPistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarPistasActionPerformed(evt);
            }
        });
        jPanelConfiguração.add(jButtonCadastrarPistas);
        jButtonCadastrarPistas.setBounds(559, 184, 160, 30);

        jButtonConfigurarPartida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonConfigurarPartida.setForeground(new java.awt.Color(0, 0, 204));
        jButtonConfigurarPartida.setText("Configurar Partida");
        jButtonConfigurarPartida.setMaximumSize(new java.awt.Dimension(134, 23));
        jButtonConfigurarPartida.setMinimumSize(new java.awt.Dimension(134, 23));
        jButtonConfigurarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfigurarPartidaActionPerformed(evt);
            }
        });
        jPanelConfiguração.add(jButtonConfigurarPartida);
        jButtonConfigurarPartida.setBounds(558, 266, 160, 30);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("CONFIGURAÇÃO DO SISTEMA");
        jPanelConfiguração.add(jLabel1);
        jLabel1.setBounds(513, 11, 270, 29);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/f1-game-2020-os-1280x720.jpg"))); // NOI18N
        jLabel36.setText("jLabel36");
        jPanelConfiguração.add(jLabel36);
        jLabel36.setBounds(0, 0, 1280, 720);

        jPanelPrincipal.add(jPanelConfiguração, "Configuracao");

        jPanelCadastroCarros.setLayout(null);

        jButtonVoltarConfiguracaoCadastroCarros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltarConfiguracaoCadastroCarros.setForeground(new java.awt.Color(204, 0, 0));
        jButtonVoltarConfiguracaoCadastroCarros.setText("Voltar");
        jButtonVoltarConfiguracaoCadastroCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarConfiguracaoCadastroCarrosActionPerformed(evt);
            }
        });
        jPanelCadastroCarros.add(jButtonVoltarConfiguracaoCadastroCarros);
        jButtonVoltarConfiguracaoCadastroCarros.setBounds(590, 290, 122, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CADASTRAR CARROS");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelCadastroCarros.add(jLabel3);
        jLabel3.setBounds(549, 38, 200, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("Modelo do carro:");
        jPanelCadastroCarros.add(jLabel4);
        jLabel4.setBounds(490, 120, 130, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Cor do carro:");
        jPanelCadastroCarros.add(jLabel5);
        jLabel5.setBounds(520, 80, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Marca do carro:");
        jPanelCadastroCarros.add(jLabel6);
        jLabel6.setBounds(500, 160, 120, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("Numero do carro:");
        jPanelCadastroCarros.add(jLabel7);
        jLabel7.setBounds(490, 200, 130, 17);

        jTextFieldCorDoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorDoCarroActionPerformed(evt);
            }
        });
        jPanelCadastroCarros.add(jTextFieldCorDoCarro);
        jTextFieldCorDoCarro.setBounds(630, 70, 159, 30);
        jPanelCadastroCarros.add(jTextFieldModeloDoCarro);
        jTextFieldModeloDoCarro.setBounds(630, 110, 159, 30);
        jPanelCadastroCarros.add(jTextFieldMarcaDoCarro);
        jTextFieldMarcaDoCarro.setBounds(630, 150, 159, 30);
        jPanelCadastroCarros.add(jTextFieldNumeroDoCarro);
        jTextFieldNumeroDoCarro.setBounds(630, 190, 159, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 51));
        jButton1.setText("Confirmar");
        jPanelCadastroCarros.add(jButton1);
        jButton1.setBounds(590, 250, 122, 23);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/f1-game-2020-os-1280x720.jpg"))); // NOI18N
        jLabel37.setText("jLabel37");
        jPanelCadastroCarros.add(jLabel37);
        jLabel37.setBounds(0, 0, 1280, 720);

        jPanelPrincipal.add(jPanelCadastroCarros, "CadastroCarros");

        jPanelCadastroEquipe.setLayout(null);

        jButtonVoltarConfiguracaoCadastroEquipe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltarConfiguracaoCadastroEquipe.setForeground(new java.awt.Color(204, 0, 0));
        jButtonVoltarConfiguracaoCadastroEquipe.setText("Voltar");
        jButtonVoltarConfiguracaoCadastroEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarConfiguracaoCadastroEquipeActionPerformed(evt);
            }
        });
        jPanelCadastroEquipe.add(jButtonVoltarConfiguracaoCadastroEquipe);
        jButtonVoltarConfiguracaoCadastroEquipe.setBounds(578, 357, 122, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CADASTRAR EQUIPE");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelCadastroEquipe.add(jLabel8);
        jLabel8.setBounds(550, 36, 185, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("ID da Equipe:");
        jPanelCadastroEquipe.add(jLabel2);
        jLabel2.setBounds(502, 94, 120, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Nome da Equipe:");
        jPanelCadastroEquipe.add(jLabel9);
        jLabel9.setBounds(482, 132, 140, 17);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 255));
        jLabel10.setText("Nacionalidade da Equipe:");
        jPanelCadastroEquipe.add(jLabel10);
        jLabel10.setBounds(432, 170, 190, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("Ano:");
        jPanelCadastroEquipe.add(jLabel11);
        jLabel11.setBounds(572, 205, 50, 21);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("Apelido da Equipe:");
        jPanelCadastroEquipe.add(jLabel12);
        jLabel12.setBounds(482, 244, 140, 20);
        jPanelCadastroEquipe.add(jTextFieldIDdaEquipe);
        jTextFieldIDdaEquipe.setBounds(626, 81, 101, 30);
        jPanelCadastroEquipe.add(jTextFieldNacionalidade);
        jTextFieldNacionalidade.setBounds(626, 157, 101, 30);
        jPanelCadastroEquipe.add(jTextFieldAno);
        jTextFieldAno.setBounds(626, 196, 101, 30);
        jPanelCadastroEquipe.add(jTextFieldNomeDaEquipe);
        jTextFieldNomeDaEquipe.setBounds(626, 119, 101, 30);

        jTextFieldApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApelidoActionPerformed(evt);
            }
        });
        jPanelCadastroEquipe.add(jTextFieldApelido);
        jTextFieldApelido.setBounds(626, 234, 101, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 0));
        jButton2.setText("Confirmar");
        jPanelCadastroEquipe.add(jButton2);
        jButton2.setBounds(578, 316, 122, 25);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 255));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/f1-game-2020-os-1280x720.jpg"))); // NOI18N
        jLabel38.setText("jLabel38");
        jPanelCadastroEquipe.add(jLabel38);
        jLabel38.setBounds(0, 0, 1280, 720);

        jPanelPrincipal.add(jPanelCadastroEquipe, "CadastroEquipe");

        jPanelConfigurarPartida.setLayout(null);

        jButtonVoltarConfiguracaoConfigurarPartida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltarConfiguracaoConfigurarPartida.setForeground(new java.awt.Color(204, 0, 0));
        jButtonVoltarConfiguracaoConfigurarPartida.setText("Voltar");
        jButtonVoltarConfiguracaoConfigurarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarConfiguracaoConfigurarPartidaActionPerformed(evt);
            }
        });
        jPanelConfigurarPartida.add(jButtonVoltarConfiguracaoConfigurarPartida);
        jButtonVoltarConfiguracaoConfigurarPartida.setBounds(600, 280, 110, 25);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("CONFIGURAR PARTIDA");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelConfigurarPartida.add(jLabel13);
        jLabel13.setBounds(541, 30, 211, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("Numero de Voltas:");
        jPanelConfigurarPartida.add(jLabel14);
        jLabel14.setBounds(450, 100, 140, 17);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("Pista:");
        jPanelConfigurarPartida.add(jLabel15);
        jLabel15.setBounds(540, 140, 50, 17);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Duração da Partida:");
        jPanelConfigurarPartida.add(jLabel16);
        jLabel16.setBounds(580, 165, 136, 17);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("Horas:");
        jPanelConfigurarPartida.add(jLabel17);
        jLabel17.setBounds(490, 200, 60, 17);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("Minutos:");
        jPanelConfigurarPartida.add(jLabel18);
        jLabel18.setBounds(600, 200, 70, 17);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("Segundos:");
        jPanelConfigurarPartida.add(jLabel19);
        jLabel19.setBounds(720, 200, 80, 17);
        jPanelConfigurarPartida.add(jTextFieldNumeroDeVoltas);
        jTextFieldNumeroDeVoltas.setBounds(594, 89, 146, 30);
        jPanelConfigurarPartida.add(jTextFieldPista);
        jTextFieldPista.setBounds(594, 127, 146, 30);
        jPanelConfigurarPartida.add(jTextFieldHoras);
        jTextFieldHoras.setBounds(538, 200, 52, 20);
        jPanelConfigurarPartida.add(jTextFieldMinutos);
        jTextFieldMinutos.setBounds(667, 200, 52, 20);
        jPanelConfigurarPartida.add(jTextFieldSegundos);
        jTextFieldSegundos.setBounds(800, 200, 52, 20);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 153, 0));
        jButton3.setText("Confirmar");
        jPanelConfigurarPartida.add(jButton3);
        jButton3.setBounds(600, 240, 110, 30);

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 255));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/f1-game-2020-os-1280x720.jpg"))); // NOI18N
        jLabel39.setText("jLabel39");
        jPanelConfigurarPartida.add(jLabel39);
        jLabel39.setBounds(0, 0, 1280, 720);

        jPanelPrincipal.add(jPanelConfigurarPartida, "ConfigurarPartida");

        jPanelCadastroPiloto.setLayout(null);

        jButtonVoltarConfiguracaoCadastroPiloto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltarConfiguracaoCadastroPiloto.setForeground(new java.awt.Color(204, 0, 0));
        jButtonVoltarConfiguracaoCadastroPiloto.setText("Voltar");
        jButtonVoltarConfiguracaoCadastroPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarConfiguracaoCadastroPilotoActionPerformed(evt);
            }
        });
        jPanelCadastroPiloto.add(jButtonVoltarConfiguracaoCadastroPiloto);
        jButtonVoltarConfiguracaoCadastroPiloto.setBounds(600, 520, 106, 25);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("CADASTRAR PILOTO");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelCadastroPiloto.add(jLabel20);
        jLabel20.setBounds(559, 60, 190, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("Nome do Piloto:");
        jPanelCadastroPiloto.add(jLabel21);
        jLabel21.setBounds(460, 110, 150, 17);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("Equipe do Piloto:");
        jPanelCadastroPiloto.add(jLabel22);
        jLabel22.setBounds(450, 150, 160, 17);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 255));
        jLabel23.setText("Apelido:");
        jPanelCadastroPiloto.add(jLabel23);
        jLabel23.setBounds(510, 270, 110, 17);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 255));
        jLabel24.setText("Data De Nascimento:");
        jPanelCadastroPiloto.add(jLabel24);
        jLabel24.setBounds(420, 310, 180, 17);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 255));
        jLabel25.setText("ID do Piloto:");
        jPanelCadastroPiloto.add(jLabel25);
        jLabel25.setBounds(480, 190, 140, 17);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 255));
        jLabel26.setText("Nacionalidade:");
        jPanelCadastroPiloto.add(jLabel26);
        jLabel26.setBounds(470, 230, 150, 17);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 255));
        jLabel27.setText("Equipe:");
        jPanelCadastroPiloto.add(jLabel27);
        jLabel27.setBounds(510, 390, 120, 17);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 255));
        jLabel28.setText("Carro:");
        jPanelCadastroPiloto.add(jLabel28);
        jLabel28.setBounds(520, 350, 110, 17);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 255));
        jLabel29.setText("O piloto está em atividade?:");
        jPanelCadastroPiloto.add(jLabel29);
        jLabel29.setBounds(370, 420, 220, 17);
        jPanelCadastroPiloto.add(jTextFieldNomeDoPiloto);
        jTextFieldNomeDoPiloto.setBounds(602, 99, 169, 30);
        jPanelCadastroPiloto.add(jTextFieldEquipeDoPiloto);
        jTextFieldEquipeDoPiloto.setBounds(600, 140, 169, 30);
        jPanelCadastroPiloto.add(jTextFieldIDDoPiloto);
        jTextFieldIDDoPiloto.setBounds(600, 180, 169, 30);
        jPanelCadastroPiloto.add(jTextFieldNacionalidadeDoPiloto);
        jTextFieldNacionalidadeDoPiloto.setBounds(600, 220, 169, 30);
        jPanelCadastroPiloto.add(jTextFieldApelidoDoPiloto);
        jTextFieldApelidoDoPiloto.setBounds(600, 260, 169, 30);
        jPanelCadastroPiloto.add(jTextFieldDataDeNascimento);
        jTextFieldDataDeNascimento.setBounds(600, 300, 169, 30);
        jPanelCadastroPiloto.add(jTextFieldCarro);
        jTextFieldCarro.setBounds(600, 340, 169, 30);
        jPanelCadastroPiloto.add(jTextFieldEquipe);
        jTextFieldEquipe.setBounds(600, 380, 169, 30);

        jComboBoxStatusPiloto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NAO" }));
        jComboBoxStatusPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusPilotoActionPerformed(evt);
            }
        });
        jPanelCadastroPiloto.add(jComboBoxStatusPiloto);
        jComboBoxStatusPiloto.setBounds(600, 420, 70, 20);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 204, 51));
        jButton4.setText("Confirmar");
        jPanelCadastroPiloto.add(jButton4);
        jButton4.setBounds(600, 470, 106, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 255));
        jLabel30.setText("\"dd/mm/aaaa\"");
        jPanelCadastroPiloto.add(jLabel30);
        jLabel30.setBounds(780, 310, 150, 17);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/f1-game-2020-os-1280x720.jpg"))); // NOI18N
        jLabel40.setText("jLabel40");
        jPanelCadastroPiloto.add(jLabel40);
        jLabel40.setBounds(0, 0, 1280, 720);

        jPanelPrincipal.add(jPanelCadastroPiloto, "CadastroPiloto");

        jPanelCadastroPista.setLayout(null);

        jButtonVoltarConfiguracaoCadastroPista.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltarConfiguracaoCadastroPista.setForeground(new java.awt.Color(204, 0, 0));
        jButtonVoltarConfiguracaoCadastroPista.setText("Voltar");
        jButtonVoltarConfiguracaoCadastroPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarConfiguracaoCadastroPistaActionPerformed(evt);
            }
        });
        jPanelCadastroPista.add(jButtonVoltarConfiguracaoCadastroPista);
        jButtonVoltarConfiguracaoCadastroPista.setBounds(590, 290, 106, 25);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 204, 51));
        jButton5.setText("Confirmar");
        jPanelCadastroPista.add(jButton5);
        jButton5.setBounds(590, 250, 106, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("CADASTRAR PISTA");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelCadastroPista.add(jLabel31);
        jLabel31.setBounds(558, 47, 180, 22);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 255));
        jLabel32.setText("ID da Pista:");
        jPanelCadastroPista.add(jLabel32);
        jLabel32.setBounds(540, 120, 90, 17);

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 255));
        jLabel33.setText("Pais da Pista:");
        jPanelCadastroPista.add(jLabel33);
        jLabel33.setBounds(530, 160, 100, 17);

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 255));
        jLabel34.setText("Nome da Pista:");
        jPanelCadastroPista.add(jLabel34);
        jLabel34.setBounds(520, 200, 110, 20);
        jPanelCadastroPista.add(jTextFieldIDPista);
        jTextFieldIDPista.setBounds(630, 110, 100, 30);
        jPanelCadastroPista.add(jTextFieldPaisDaPista);
        jTextFieldPaisDaPista.setBounds(630, 150, 100, 30);
        jPanelCadastroPista.add(jTextFieldNomeDaPista);
        jTextFieldNomeDaPista.setBounds(630, 190, 100, 30);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/f1-game-2020-os-1280x720.jpg"))); // NOI18N
        jLabel43.setText("jLabel43");
        jPanelCadastroPista.add(jLabel43);
        jLabel43.setBounds(0, 0, 1280, 720);

        jPanelPrincipal.add(jPanelCadastroPista, "CadastroPista");

        jPanelConectarRFID.setPreferredSize(new java.awt.Dimension(1280, 700));
        jPanelConectarRFID.setLayout(null);

        jButtonVoltarConfiguracaoRFID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonVoltarConfiguracaoRFID.setForeground(new java.awt.Color(204, 0, 0));
        jButtonVoltarConfiguracaoRFID.setText("Voltar");
        jButtonVoltarConfiguracaoRFID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarConfiguracaoRFIDActionPerformed(evt);
            }
        });
        jPanelConectarRFID.add(jButtonVoltarConfiguracaoRFID);
        jButtonVoltarConfiguracaoRFID.setBounds(610, 470, 100, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("CONECTAR AO LEITOR RFID");
        jLabel35.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelConectarRFID.add(jLabel35);
        jLabel35.setBounds(533, 35, 260, 22);

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 0, 255));
        jLabel44.setText("Potência do sinal:");
        jPanelConectarRFID.add(jLabel44);
        jLabel44.setBounds(470, 180, 130, 17);

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(0, 0, 255));
        jLabel45.setText("IP:");
        jPanelConectarRFID.add(jLabel45);
        jLabel45.setBounds(560, 100, 50, 17);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 255));
        jLabel46.setText("Antena:");
        jPanelConectarRFID.add(jLabel46);
        jLabel46.setBounds(530, 380, 80, 20);

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 0, 255));
        jLabel47.setText("Porta serial:");
        jPanelConectarRFID.add(jLabel47);
        jLabel47.setBounds(500, 300, 100, 20);

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 255));
        jLabel48.setText("Taxa em baud:");
        jPanelConectarRFID.add(jLabel48);
        jLabel48.setBounds(480, 220, 120, 17);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 255));
        jLabel49.setText("Protocolo:");
        jPanelConectarRFID.add(jLabel49);
        jLabel49.setBounds(510, 260, 90, 20);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 255));
        jLabel50.setText("Porta de rede:");
        jPanelConectarRFID.add(jLabel50);
        jLabel50.setBounds(490, 140, 110, 17);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 0, 255));
        jLabel51.setText("Região:");
        jPanelConectarRFID.add(jLabel51);
        jLabel51.setBounds(530, 340, 80, 20);

        jTextFieldAntena.setToolTipText("");
        jPanelConectarRFID.add(jTextFieldAntena);
        jTextFieldAntena.setBounds(600, 370, 140, 30);

        jTextFieldIP.setToolTipText("");
        jTextFieldIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPActionPerformed(evt);
            }
        });
        jPanelConectarRFID.add(jTextFieldIP);
        jTextFieldIP.setBounds(600, 90, 140, 30);

        jTextFieldPortaDeRede.setToolTipText("");
        jPanelConectarRFID.add(jTextFieldPortaDeRede);
        jTextFieldPortaDeRede.setBounds(600, 130, 140, 30);

        jTextFieldTaxaEmBaud.setToolTipText("");
        jPanelConectarRFID.add(jTextFieldTaxaEmBaud);
        jTextFieldTaxaEmBaud.setBounds(600, 210, 140, 30);

        jTextFieldPotenciaDoSinal.setToolTipText("");
        jPanelConectarRFID.add(jTextFieldPotenciaDoSinal);
        jTextFieldPotenciaDoSinal.setBounds(600, 170, 140, 30);

        jTextFieldProtocolo.setToolTipText("");
        jPanelConectarRFID.add(jTextFieldProtocolo);
        jTextFieldProtocolo.setBounds(600, 250, 140, 30);

        jTextFieldPortaSerial.setToolTipText("");
        jPanelConectarRFID.add(jTextFieldPortaSerial);
        jTextFieldPortaSerial.setBounds(600, 290, 140, 30);

        jTextFieldRegiao.setToolTipText("");
        jPanelConectarRFID.add(jTextFieldRegiao);
        jTextFieldRegiao.setBounds(600, 330, 140, 30);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 204, 51));
        jButton6.setText("Conectar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanelConectarRFID.add(jButton6);
        jButton6.setBounds(610, 430, 100, 30);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/f1-game-2020-os-1280x720.jpg"))); // NOI18N
        jLabel42.setText("jLabel42");
        jLabel42.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanelConectarRFID.add(jLabel42);
        jLabel42.setBounds(0, 0, 1280, 720);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 0, 255));
        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/f1-game-2020-os-1280x720.jpg"))); // NOI18N
        jLabel41.setText("jLabel41");
        jPanelConectarRFID.add(jLabel41);
        jLabel41.setBounds(0, 0, 1280, 720);

        jPanelPrincipal.add(jPanelConectarRFID, "ConectarRFID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarCarrosActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "CadastroCarros");
    }//GEN-LAST:event_jButtonCadastrarCarrosActionPerformed

    private void jButtonConectarRFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarRFIDActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "ConectarRFID");
    }//GEN-LAST:event_jButtonConectarRFIDActionPerformed

    private void jButtonVoltarConfiguracaoCadastroCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarConfiguracaoCadastroCarrosActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "Configuracao");
    }//GEN-LAST:event_jButtonVoltarConfiguracaoCadastroCarrosActionPerformed

    private void jButtonCadastrarPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarPilotosActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "CadastroPiloto");
    }//GEN-LAST:event_jButtonCadastrarPilotosActionPerformed

    private void jButtonCadastrarPistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarPistasActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "CadastroPista");
    }//GEN-LAST:event_jButtonCadastrarPistasActionPerformed

    private void jButtonCadastrarEquipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarEquipesActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "CadastroEquipe");
    }//GEN-LAST:event_jButtonCadastrarEquipesActionPerformed

    private void jButtonConfigurarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfigurarPartidaActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "ConfigurarPartida");
    }//GEN-LAST:event_jButtonConfigurarPartidaActionPerformed

    private void jButtonVoltarConfiguracaoConfigurarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarConfiguracaoConfigurarPartidaActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "Configuracao");
    }//GEN-LAST:event_jButtonVoltarConfiguracaoConfigurarPartidaActionPerformed

    private void jButtonVoltarConfiguracaoCadastroPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarConfiguracaoCadastroPistaActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "Configuracao");
    }//GEN-LAST:event_jButtonVoltarConfiguracaoCadastroPistaActionPerformed

    private void jButtonVoltarConfiguracaoRFIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarConfiguracaoRFIDActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "Configuracao");
    }//GEN-LAST:event_jButtonVoltarConfiguracaoRFIDActionPerformed

    private void jTextFieldApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApelidoActionPerformed

    private void jButtonVoltarConfiguracaoCadastroEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarConfiguracaoCadastroEquipeActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "Configuracao");
    }//GEN-LAST:event_jButtonVoltarConfiguracaoCadastroEquipeActionPerformed

    private void jButtonVoltarConfiguracaoCadastroPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarConfiguracaoCadastroPilotoActionPerformed
        CardLayout cl = (CardLayout) this.jPanelPrincipal.getLayout();
        cl.show(this.jPanelPrincipal, "Configuracao");
    }//GEN-LAST:event_jButtonVoltarConfiguracaoCadastroPilotoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       ClienteTCP cliente =  new ClienteTCP(this.jTextFieldIP.getText(), Integer.parseInt(this.jTextFieldPortaDeRede.getText()));
       cliente.estabelecerConexão();
       JSONObject configuracaoRFID = new JSONObject();
       configuracaoRFID.put("potencia", Integer.parseInt(this.jTextFieldPotenciaDoSinal.getText()));
       configuracaoRFID.put("taxa", Integer.parseInt(this.jTextFieldTaxaEmBaud.getText()));
       configuracaoRFID.put("protocolo", this.jTextFieldProtocolo.getText());
       configuracaoRFID.put("regiao", this.jTextFieldRegiao.getText());
       configuracaoRFID.put("porta", this.jTextFieldPortaSerial.getText());
       configuracaoRFID.put("antena", Integer.parseInt(this.jTextFieldAntena.getText()));
       String conteudoJSON = configuracaoRFID.toString();
       //tamo aqui testando né
       JOptionPane.showMessageDialog(null,"configuracoes salvas: potencia do sinal: "+"\ntaxa em baud: "+configuracaoRFID.getInt("taxa")+"\nprotocolo: "+configuracaoRFID.getString("protocolo")+"\nregiao: "+configuracaoRFID.get("regiao")+"\nporta serial: "+configuracaoRFID.get("porta")+"\nantena: "+configuracaoRFID.get("antena"));
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBoxStatusPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusPilotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusPilotoActionPerformed

    private void jTextFieldIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPActionPerformed

    private void jTextFieldCorDoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorDoCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorDoCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonCadastrarCarros;
    private javax.swing.JButton jButtonCadastrarEquipes;
    private javax.swing.JButton jButtonCadastrarPilotos;
    private javax.swing.JButton jButtonCadastrarPistas;
    private javax.swing.JButton jButtonConectarRFID;
    private javax.swing.JButton jButtonConfigurarPartida;
    private javax.swing.JButton jButtonVoltarConfiguracaoCadastroCarros;
    private javax.swing.JButton jButtonVoltarConfiguracaoCadastroEquipe;
    private javax.swing.JButton jButtonVoltarConfiguracaoCadastroPiloto;
    private javax.swing.JButton jButtonVoltarConfiguracaoCadastroPista;
    private javax.swing.JButton jButtonVoltarConfiguracaoConfigurarPartida;
    private javax.swing.JButton jButtonVoltarConfiguracaoRFID;
    private javax.swing.JComboBox<String> jComboBoxStatusPiloto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCadastroCarros;
    private javax.swing.JPanel jPanelCadastroEquipe;
    private javax.swing.JPanel jPanelCadastroPiloto;
    private javax.swing.JPanel jPanelCadastroPista;
    private javax.swing.JPanel jPanelConectarRFID;
    private javax.swing.JPanel jPanelConfigurarPartida;
    private javax.swing.JPanel jPanelConfiguração;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldAntena;
    private javax.swing.JTextField jTextFieldApelido;
    private javax.swing.JTextField jTextFieldApelidoDoPiloto;
    private javax.swing.JTextField jTextFieldCarro;
    private javax.swing.JTextField jTextFieldCorDoCarro;
    private javax.swing.JTextField jTextFieldDataDeNascimento;
    private javax.swing.JTextField jTextFieldEquipe;
    private javax.swing.JTextField jTextFieldEquipeDoPiloto;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldIDDoPiloto;
    private javax.swing.JTextField jTextFieldIDPista;
    private javax.swing.JTextField jTextFieldIDdaEquipe;
    private javax.swing.JTextField jTextFieldIP;
    private javax.swing.JTextField jTextFieldMarcaDoCarro;
    private javax.swing.JTextField jTextFieldMinutos;
    private javax.swing.JTextField jTextFieldModeloDoCarro;
    private javax.swing.JTextField jTextFieldNacionalidade;
    private javax.swing.JTextField jTextFieldNacionalidadeDoPiloto;
    private javax.swing.JTextField jTextFieldNomeDaEquipe;
    private javax.swing.JTextField jTextFieldNomeDaPista;
    private javax.swing.JTextField jTextFieldNomeDoPiloto;
    private javax.swing.JTextField jTextFieldNumeroDeVoltas;
    private javax.swing.JTextField jTextFieldNumeroDoCarro;
    private javax.swing.JTextField jTextFieldPaisDaPista;
    private javax.swing.JTextField jTextFieldPista;
    private javax.swing.JTextField jTextFieldPortaDeRede;
    private javax.swing.JTextField jTextFieldPortaSerial;
    private javax.swing.JTextField jTextFieldPotenciaDoSinal;
    private javax.swing.JTextField jTextFieldProtocolo;
    private javax.swing.JTextField jTextFieldRegiao;
    private javax.swing.JTextField jTextFieldSegundos;
    private javax.swing.JTextField jTextFieldTaxaEmBaud;
    // End of variables declaration//GEN-END:variables
}
